{ targetPath }:
{ config, lib, ... }:
let
  cfg = config.nixporn;
  target = "fcitx5";
  colorscheme = cfg.colorscheme;
  hasSpecific = builtins.pathExists (targetPath + "/${colorscheme}.nix");
  fcitx5Enabled =
    (
      config.i18n.inputMethod ? enable
      && config.i18n.inputMethod.enable
      && config.i18n.inputMethod.type == "fcitx5"
    )
    || (config.i18n.inputMethod ? enabled && config.i18n.inputMethod.enabled == "fcitx5");
  enable = cfg.enable && cfg.${target}.enable && !hasSpecific && fcitx5Enabled;
  inherit (cfg.palette) ansi;
  themeName = "nixporn-${colorscheme}";
in
{
  config = lib.mkIf enable (
    lib.mkDefault {
      i18n.inputMethod.fcitx5 = {
        settings.addons = lib.mkIf cfg.${target}.apply {
          classicui.globalSection = {
            Theme = themeName;
            UseDarkTheme = false;
            UseAccentColor = false;
          };
        };
        themes.${themeName}.theme = {
          Metadata = {
            Name = themeName;
            Version = 0.1;
            Author = "nixporn";
            Description = "Generated by nixporn";
          };
          InputPanel = {
            NormalColor = ansi.fg;
            HighlightCandidateColor = ansi.bright_white;
            HighlightColor = ansi.black;
            HighlightBackgroundColor = ansi.magenta;
            EnableBlur = false;
            FullWidthHighlight = true;
          };
          "InputPanel/Background" = {
            Color = ansi.black;
            BorderColor = ansi.black;
            BorderWidth = 0;
          };
          "InputPanel/Highlight" = {
            Color = ansi.magenta;
            BorderColor = ansi.magenta;
            BorderWidth = 0;
          };
          Menu = {
            NormalColor = ansi.fg;
            HighlightCandidateColor = ansi.bg;
            Spacing = 0;
          };
          "Menu/Background" = {
            Color = ansi.black;
            BorderColor = ansi.black;
            BorderWidth = 0;
          };
          "Menu/Highlight" = {
            Color = ansi.fg;
            BorderColor = ansi.fg;
            BorderWidth = 0;
          };
          "Menu/Separator" = {
            Color = ansi.bg;
            BorderColor = ansi.bg;
            BorderWidth = 0;
          };
        };
      };
    }
  );
}
