{ targetPath }:
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.nixporn;
  target = "fcitx5";
  colorscheme = cfg.colorscheme;
  hasSpecific = builtins.pathExists (targetPath + "/${colorscheme}.nix");
  enable = cfg.enable && cfg.${target}.enable && !hasSpecific;
  inherit (cfg.palette) ansi;
  themeName = cfg.colorschemes.${colorscheme}.slug;
  alpha = color: "${color}00";
  iniFormat = pkgs.formats.ini { };
  iniGlobalFormat = pkgs.formats.iniWithGlobalSection { };
  classicUiFile = iniGlobalFormat.generate "fcitx5-classicui.conf" {
    globalSection = {
      Theme = themeName;
      DarkTheme = themeName;
      Font = "Sans 13";
      MenuFont = "Sans 10";
      TrayFont = "Sans 10";
      UseDarkTheme = cfg.colorschemes.${colorscheme}.polarity == "dark";
      UseAccentColor = false;
    };
  };
  themeFile = iniFormat.generate "fcitx5-${themeName}-theme.conf" {
    Metadata = {
      Name = themeName;
      Version = 0.1;
      Author = "nixporn";
      Description = "Generated by nixporn using Catppuccin-style layout";
      ScaleWithDPI = true;
    };
    InputPanel = {
      NormalColor = ansi.fg;
      HighlightCandidateColor = ansi.bg;
      HighlightColor = ansi.blue;
      HighlightBackgroundColor = ansi.black;
      Spacing = 3;
    };
    "InputPanel/Background" = {
      Color = ansi.bg;
      BorderColor = ansi.black;
      BorderWidth = 0;
    };
    "InputPanel/Background/Margin" = {
      Left = 10;
      Right = 10;
      Top = 10;
      Bottom = 10;
    };
    "InputPanel/Highlight" = {
      Color = ansi.blue;
      BorderColor = alpha ansi.blue;
      BorderWidth = 0;
    };
    "InputPanel/Highlight/Margin" = {
      Left = 18;
      Right = 18;
      Top = 8;
      Bottom = 8;
    };
    "InputPanel/TextMargin" = {
      Left = 18;
      Right = 18;
      Top = 8;
      Bottom = 8;
    };
    Menu = {
      NormalColor = ansi.fg;
      HighlightCandidateColor = ansi.bg;
      Spacing = 3;
    };
    "Menu/Background" = {
      Color = ansi.bg;
      BorderColor = alpha ansi.black;
      BorderWidth = 0;
    };
    "Menu/Background/Margin" = {
      Left = 2;
      Right = 2;
      Top = 2;
      Bottom = 2;
    };
    "Menu/ContentMargin" = {
      Left = 2;
      Right = 2;
      Top = 2;
      Bottom = 2;
    };
    "Menu/Highlight" = {
      Color = ansi.blue;
      BorderColor = alpha ansi.blue;
      BorderWidth = 0;
    };
    "Menu/Highlight/Margin" = {
      Left = 10;
      Right = 10;
      Top = 5;
      Bottom = 5;
    };
    "Menu/Separator" = {
      Color = ansi.black;
      BorderColor = alpha ansi.black;
      BorderWidth = 0;
    };
  };
in
{
  config = lib.mkIf enable {
    xdg.configFile = lib.mkIf cfg.${target}.apply {
      "fcitx5/conf/classicui.conf".source = classicUiFile;
    };
    xdg.dataFile."fcitx5/themes/${themeName}/theme.conf".source = themeFile;
  };
}
