{ targetPath }:
{ config, lib, ... }:
let
  cfg = config.nixporn;
  target = "vicinae";
  colorscheme = cfg.colorscheme;
  hasSpecific = builtins.pathExists (targetPath + "/${colorscheme}.nix");
  enable = cfg.enable && cfg.${target}.enable && !hasSpecific;
  inherit (cfg.palette) ansi;
  themeName = cfg.colorschemes.${colorscheme}.slug;
  themeConfiguration = {
    name = themeName;
  };
in
{
  config = lib.mkIf enable {
    programs.vicinae = {
      settings.theme = {
        light = themeConfiguration;
        dark = themeConfiguration;
      };
      themes.${themeName} = {
        meta = {
          name = themeName;
          description = "Generated by nixporn";
          variant = cfg.colorschemes.${colorscheme}.polarity;
        };
        colors = {
          core = {
            background = ansi.bg;
            foreground = ansi.fg;
            secondary_background = ansi.black;
            border = ansi.bright_black;
            accent = ansi.blue;
          };
          accents = {
            blue = ansi.blue;
            green = ansi.green;
            magenta = ansi.magenta;
            orange = ansi.yellow;
            purple = ansi.magenta;
            red = ansi.red;
            yellow = ansi.yellow;
            cyan = ansi.cyan;
          };
          list.item = {
            selection.background.name = ansi.black;
            selection.secondary_background = ansi.bright_black;
            hover.background = ansi.black;
          };
        };
      };
    };
  };
}
