{
  lib,
  stdenvNoCC,
  clickgen,
  hyprcursor,
  python3,
  python3Packages,
  resvg,
  source,
  variant ? "main",
  cursorThemeName ? "rose-pine-${variant}-cursors",
  baseColor ? "#191724",
  outlineColor ? "#e0def4",
}:
assert
  builtins.elem variant [
    "dawn"
    "main"
    "moon"
  ]
  || builtins.trace "Invalid Rose Pine cursor variant: ${variant}" false;
stdenvNoCC.mkDerivation {
  pname = cursorThemeName;
  version = "unstable";
  src = source;

  nativeBuildInputs = [
    clickgen
    hyprcursor
    python3
    python3Packages.tomli
    python3Packages.tomli-w
    resvg
  ];

  buildPhase = ''
    runHook preBuild

    cp -R svg themed-svg
    chmod -R u+w themed-svg
    sed -i \
      -e 's/#00FF00/${baseColor}/g' \
      -e 's/#0000FF/${outlineColor}/g' \
      themed-svg/static/*.svg themed-svg/animated/*.svg

    mkdir -p animated-svg bitmaps

    for svgFile in themed-svg/static/*.svg; do
      cursorName="$(basename "$svgFile" .svg)"
      resvg "$svgFile" "bitmaps/$cursorName.png"
    done

    for frame in $(seq 0 19); do
      angle=$((frame * 18))
      frameNumber="$(printf '%02d' $((frame + 1)))"

      for cursorName in left_ptr_watch wait; do
        sed \
          -e '/<animateTransform /d' \
          -e "s/<circle cx=\"50\"/<circle transform=\"rotate($angle 50 50)\" cx=\"50\"/" \
          "themed-svg/animated/$cursorName.svg" \
          > "animated-svg/$cursorName-$frameNumber.svg"
        resvg \
          "animated-svg/$cursorName-$frameNumber.svg" \
          "bitmaps/$cursorName-$frameNumber.png"
      done
    done

    ctgen build.toml \
      --platforms x11 \
      --bitmaps-dir bitmaps \
      --out-dir xcursor-theme \
      --theme-name '${cursorThemeName}' \
      --theme-comment 'Rosé Pine cursors generated by nixporn'

    mkdir -p hyprcursor-work/hyprcursors hyprcursor-theme
    cat > hyprcursor-work/manifest.hl <<'EOF'
    name = ${cursorThemeName}
    description = Rosé Pine cursors generated by nixporn
    version = 1
    cursors_directory = hyprcursors
    EOF

    python ${./configure.py} \
      build.toml \
      themed-svg/static \
      animated-svg \
      hyprcursor-work/hyprcursors \
      200

    hyprcursor-util \
      --create hyprcursor-work \
      --output hyprcursor-theme \
      > /dev/null

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    install -dm 0755 "$out/share/icons/${cursorThemeName}"
    cp -R "xcursor-theme/${cursorThemeName}/." "$out/share/icons/${cursorThemeName}/"
    cp -R "hyprcursor-theme/theme_${cursorThemeName}/." "$out/share/icons/${cursorThemeName}/"

    runHook postInstall
  '';

  passthru = {
    inherit cursorThemeName;
  };

  meta = {
    description = "Configurable Rosé Pine BreezeX cursor theme";
    homepage = "https://github.com/rose-pine/cursors";
    license = lib.licenses.gpl3Only;
    platforms = lib.platforms.linux;
  };
}
