{
  clickgen,
  hyprcursor,
  lib,
  python3,
  python3Packages,
  resvg,
  source,
  stdenvNoCC,
  baseColor ? "#002b36",
  outlineColor ? "#839496",
  watchBackgroundColor ? "#b58900",
  cursorThemeName ? "XCursor-Pro-Nixporn",
}:
stdenvNoCC.mkDerivation {
  pname = cursorThemeName;
  version = "unstable";
  src = source;

  nativeBuildInputs = [
    clickgen
    hyprcursor
    python3
    python3Packages.tomli
    python3Packages.tomli-w
    resvg
  ];

  buildPhase = ''
    runHook preBuild

    cp -R svg themed-svg
    chmod -R u+w themed-svg
    find themed-svg -type f -name '*.svg' -exec sed -i \
      -e 's/#00FF00/${baseColor}/g' \
      -e 's/#0000FF/${outlineColor}/g' \
      -e 's/#FF0000/${watchBackgroundColor}/g' {} +

    mkdir -p bitmaps
    while IFS= read -r svgFile; do
      resvg "$svgFile" "bitmaps/$(basename "$svgFile" .svg).png"
    done < <(find themed-svg -type f -name '*.svg' | sort)

    ctgen configs/x.build.toml \
      --platforms x11 \
      --bitmaps-dir bitmaps \
      --out-dir xcursor-theme \
      --theme-name '${cursorThemeName}' \
      --theme-comment 'XCursor-Pro generated by nixporn'

    mkdir -p hyprcursor-work/hyprcursors hyprcursor-theme
    cat > hyprcursor-work/manifest.hl <<'EOF'
    name = ${cursorThemeName}
    description = XCursor-Pro generated by nixporn
    version = 1
    cursors_directory = hyprcursors
    EOF

    python ${../cursors/configure.py} \
      configs/x.build.toml \
      bitmaps \
      hyprcursor-work/hyprcursors \
      256

    hyprcursor-util \
      --create hyprcursor-work \
      --output hyprcursor-theme \
      > /dev/null

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    install -dm 0755 "$out/share/icons/${cursorThemeName}"
    cp -R "xcursor-theme/${cursorThemeName}/." "$out/share/icons/${cursorThemeName}/"
    cp -R "hyprcursor-theme/theme_${cursorThemeName}/." "$out/share/icons/${cursorThemeName}/"

    runHook postInstall
  '';

  passthru = {
    inherit cursorThemeName;
  };

  meta = {
    description = "Configurable XCursor-Pro theme with XCursor and Hyprcursor support";
    homepage = "https://github.com/ful1e5/XCursor-pro";
    license = lib.licenses.gpl3Only;
    platforms = lib.platforms.linux;
  };
}
